import { describe, expect, mock, test } from "bun:test";

mock.module("server-only", () => ({}));

const projectsModulePromise = import("./projects");

describe("Vercel project helpers", () => {
  test("prefers a remembered project over auto-selection", async () => {
    const { pickSelectedVercelProjectId } = await projectsModulePromise;

    const projects = [
      {
        projectId: "prj_1",
        projectName: "alpha",
      },
      {
        projectId: "prj_2",
        projectName: "beta",
      },
    ];

    expect(pickSelectedVercelProjectId(projects, "prj_2")).toBe("prj_2");
    expect(pickSelectedVercelProjectId(projects)).toBeNull();
    expect(
      pickSelectedVercelProjectId(
        [{ projectId: "prj_3", projectName: "solo" }],
        null,
      ),
    ).toBe("prj_3");
  });

  test("keeps only development env vars and prefers the most specific target", async () => {
    const { selectDevelopmentProjectEnvironmentVariables } =
      await projectsModulePromise;

    const envVars = selectDevelopmentProjectEnvironmentVariables([
      {
        key: "SHARED_KEY",
        value: "fallback",
        target: ["preview", "development"],
        updatedAt: 1,
      },
      {
        key: "SHARED_KEY",
        value: "specific",
        target: "development",
        updatedAt: 2,
      },
      {
        key: "IGNORED_KEY",
        value: "prod-only",
        target: "production",
      },
      {
        key: "ANOTHER_KEY",
        value: "kept",
        target: ["development"],
      },
    ]);

    expect(envVars).toEqual([
      {
        key: "ANOTHER_KEY",
        value: "kept",
        target: ["development"],
      },
      {
        key: "SHARED_KEY",
        value: "specific",
        target: "development",
        updatedAt: 2,
      },
    ]);
  });

  test("renders dotenv content with stable ordering and escaped values", async () => {
    const { createDotEnvLocalFileContent } = await projectsModulePromise;

    const content = createDotEnvLocalFileContent([
      {
        key: "SECOND_KEY",
        value: 'value with "quotes"',
      },
      {
        key: "FIRST_KEY",
        value: "line 1\nline 2",
      },
    ]);

    expect(content).toContain(
      "# Generated by Open Harness from Vercel Development environment variables.",
    );
    expect(content).toContain('SECOND_KEY="value with \\\"quotes\\\""');
    expect(content).toContain('FIRST_KEY="line 1\\nline 2"');
    expect(content.endsWith("\n")).toBe(true);
  });
});
